apiVersion: v1
kind: Pod
metadata:
  name: sqs-access-test
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["sleep", "3600"]
      env:
        - name: AWS_REGION
          value: "eu-west-1"
